### ISSUE TITLE
Default white prefab needs to be shown as first selected option

### ISSUE THREAD

**Issue by JakeCulp** [by-erinmichelle/master25-project-management#165]
![Screen Shot 2019-02-23 at 10.35.45 PM.png](https://images.zenhubusercontent.com/5bcb4973ba8f76415ef5d02a/5aff9e55-9a78-486f-88e7-287cb9504dad)

Explanation: Beginning color is white (is default prefab), what happens after I change color to red? White prefab is gone and I can't get it back. white prefab should be first option is selection of colors.

**Comment by by-erinmichelle** [comment]
👍

**Comment by by-erinmichelle** [comment]
let's discuss tomorrow @JakeCulp
