### ISSUE TITLE
Reach out to Interiors Expert

### ISSUE THREAD

**Issue by brendanluu** [by-erinmichelle/master25-project-management#24]

**Comment by JakeCulp** [comment]
Reached out to Matt Neff
https://www.design.upenn.edu/fine-arts/undergraduate/people/matt-neff

Reached out to Paul Farber
https://www.design.upenn.edu/fine-arts/undergraduate/people/paul-farber

Reached out to Ada Tremonte
https://drexel.edu/westphal/about/directory/TremonteAda/
